reviewers:
  # Reviewer groups each of which has a list of GitHub usernames
  groups:
    prodeng_team:
      - abbymwalker # username
      - sibieler34 # username
      - roscioli # username
      - pelzhaus # username
      - senorbacon # username
      - allen-pinwheel # username
      - team:prod-eng # GitHub team
    automation:
      - pinwheel-it-svc

  # Reviewers per author.
  # Keys are reviewees, each of which has an array of reviewers.
  per_author:
    prodeng_team:
      - prodeng_team # group
    automation:
      - prodeng_team
